/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /orders — 내 주문 목록 */
        get: operations["OrderController_listMyOrders"];
        put?: never;
        /** POST /orders — 주문 생성 */
        post: operations["OrderController_createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /orders/:orderId — 주문 상세 */
        get: operations["OrderController_getDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /orders/:orderId/cancel — 주문 취소 (구매자) */
        post: operations["OrderController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /orders/:orderId/complete — 구매 확정 (구매자) */
        post: operations["OrderController_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /seller/orders — 판매자 수주 목록 */
        get: operations["SellerOrderController_listSellerOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /seller/orders/:orderId — 판매자 단건 주문 상세 (items 포함, 본인 소유) */
        get: operations["SellerOrderController_getSellerOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/orders/{orderId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /seller/orders/:orderId/confirm — 판매자 주문 확인 (pending → preparing) */
        post: operations["SellerOrderController_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sellers/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 판매자 등록 (FR-011, SC-013) */
        post: operations["SellerController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sellers/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 판매자 프로필 조회 (FR-012, SC-014) */
        get: operations["SellerController_getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 내 판매자 프로필 수정 (FR-013, SC-015) */
        patch: operations["SellerController_updateMyProfile"];
        trace?: never;
    };
    "/sellers/me/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 심사 상태 조회 (FR-014, SC-016) */
        get: operations["SellerController_getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sellers/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 승인 (FR-015, SC-017) — SEC-001 수정: AdminGuard 적용.
         *     ADMIN_USER_IDS 미포함 사용자 → 403. fail-closed(미설정 시 전원 거부).
         */
        patch: operations["SellerController_approve"];
        trace?: never;
    };
    "/sellers/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 거부 (FR-016, SC-018) — SEC-001 수정: AdminGuard 적용.
         *     ADMIN_USER_IDS 미포함 사용자 → 403. fail-closed(미설정 시 전원 거부).
         */
        patch: operations["SellerController_reject"];
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductController_listPublic"];
        put?: never;
        post: operations["ProductController_createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /products/:id — 상세 조회, 인증 시 조회 기록 */
        get: operations["ProductController_getDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** PATCH /products/:id — 상품 수정 (소유자만) */
        patch: operations["ProductController_updateProduct"];
        trace?: never;
    };
    "/products/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** PATCH /products/:id/publish — DRAFT/INACTIVE → ACTIVE */
        patch: operations["ProductController_publish"];
        trace?: never;
    };
    "/products/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** PATCH /products/:id/deactivate — ACTIVE/OUT_OF_STOCK → INACTIVE */
        patch: operations["ProductController_deactivate"];
        trace?: never;
    };
    "/products/{id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProductController_addVariant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/variants/{variantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** DELETE /products/:id/variants/:variantId — variant 삭제 */
        delete: operations["ProductController_deleteVariant"];
        options?: never;
        head?: never;
        /** PATCH /products/:id/variants/:variantId — variant 수정 */
        patch: operations["ProductController_updateVariant"];
        trace?: never;
    };
    "/products/{id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProductController_addImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/images/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** DELETE /products/:id/images/:imageId — 이미지 삭제 */
        delete: operations["ProductController_deleteImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CategoriesController_listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sellers/me/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SellerProductController_listMyProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/{variantId}/stock-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /inventory/:variantId/stock-in — 재고 입고 (APPROVED 판매자 + 소유 variant, FR-030, SC-041, SEC-002) */
        post: operations["InventoryController_stockIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/{variantId}/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /inventory/:variantId/stock — 재고 수량 조회 (APPROVED 판매자 + 소유 variant, FR-031, SEC-002) */
        get: operations["InventoryController_getStock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /cart — 장바구니 조회 */
        get: operations["CartController_getCart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /cart/items — 장바구니 항목 추가 */
        post: operations["CartController_addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items/{variantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** PUT /cart/items/:variantId — 수량 변경 (0이면 삭제) */
        put: operations["CartController_updateQuantity"];
        post?: never;
        /** DELETE /cart/items/:variantId — 항목 제거 */
        delete: operations["CartController_removeItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/coupons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /admin/coupons — 관리자 쿠폰 목록 (FR-007) */
        get: operations["AdminCouponController_listCoupons"];
        put?: never;
        /** POST /admin/coupons — 관리자 쿠폰 생성 (FR-001) */
        post: operations["AdminCouponController_createCoupon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/coupons/{id}/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /admin/coupons/:id/issue — 관리자 발급 (FR-003) */
        post: operations["AdminCouponController_issueCoupon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sellers/me/coupons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /sellers/me/coupons — 판매자 쿠폰 목록 (FR-006) */
        get: operations["SellerCouponController_listCoupons"];
        put?: never;
        /** POST /sellers/me/coupons — 판매자 쿠폰 생성 (FR-002) */
        post: operations["SellerCouponController_createCoupon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sellers/me/coupons/{id}/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /sellers/me/coupons/:id/issue — 판매자 발급 (FR-004) */
        post: operations["SellerCouponController_issueCoupon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/coupons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /users/me/coupons — 내 쿠폰 목록 (FR-005) */
        get: operations["UserCouponController_listMyCoupons"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /payments — 결제 생성.
         *     Idempotency-Key 헤더(UUID v4)를 우선, 없으면 body.idempotencyKey 사용.
         *     비-UUID v4 → 400 (FR-031, SC-035).
         *     금액은 서버 측 order.totalAmount 에서 취득 (외부 입력 불신).
         */
        post: operations["PaymentController_pay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UserController_updateMe"];
        trace?: never;
    };
    "/users/me/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_listAddresses"];
        put?: never;
        post: operations["UserController_createAddress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/addresses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["UserController_deleteAddress"];
        options?: never;
        head?: never;
        patch: operations["UserController_updateAddress"];
        trace?: never;
    };
    "/users/me/addresses/{id}/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UserController_setDefaultAddress"];
        trace?: never;
    };
    "/users/me/wishlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_listWishlist"];
        put?: never;
        post: operations["UserController_addWishlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/wishlist/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["UserController_removeWishlist"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/recent-views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_listRecentViews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shipments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /shipments?orderId= — 주문 기준 송장 조회 (구매자/판매자). 미존재 시 null. */
        get: operations["ShippingController_getByOrder"];
        put?: never;
        /** POST /shipments — 송장 등록 (APPROVED 판매자) */
        post: operations["ShippingController_createShipment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shipments/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** PATCH /shipments/:id/status — 배송 상태 업데이트 (판매자) */
        patch: operations["ShippingController_updateStatus"];
        trace?: never;
    };
    "/shipments/{id}/tracking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /shipments/:id/tracking — 배송 추적 조회 (구매자 본인 또는 판매자) */
        get: operations["ShippingController_getTracking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /settlements — 판매자 본인 정산 내역 (본인만) */
        get: operations["SettlementController_listMySettlements"];
        put?: never;
        /** POST /settlements — 정산 생성 (관리자 전용) */
        post: operations["SettlementController_createSettlement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /admin/settlements — 전체 정산 내역 (관리자) */
        get: operations["AdminSettlementController_listAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /reviews — 리뷰 작성 (FR-021~FR-023) */
        post: operations["ReviewController_createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** DELETE /reviews/:id — 리뷰 삭제 (FR-024) */
        delete: operations["ReviewController_deleteReview"];
        options?: never;
        head?: never;
        /** PATCH /reviews/:id — 리뷰 수정 (FR-024) */
        patch: operations["ReviewController_updateReview"];
        trace?: never;
    };
    "/reviews/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /reviews/me — 내 리뷰 목록 (FR-026) */
        get: operations["ReviewController_listMyReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /products/:productId/reviews — 상품 리뷰 목록 (FR-025) */
        get: operations["ProductReviewController_listProductReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /search/products — 키워드·카테고리·가격·정렬 필터 + offset 페이지네이션 */
        get: operations["SearchController_searchProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /notifications — 본인 알림 목록 (미읽음 우선/최신순) */
        get: operations["NotificationController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** PATCH /notifications/read-all — 본인 전체 읽음 */
        patch: operations["NotificationController_markAllRead"];
        trace?: never;
    };
    "/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** PATCH /notifications/:id/read — 본인 알림 읽음 처리 */
        patch: operations["NotificationController_markRead"];
        trace?: never;
    };
    "/files/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /files/presign — presigned upload URL + 메타데이터(PENDING) 생성 */
        post: operations["FileController_presign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /files/:id — 파일 메타 조회 (소유자 전용) */
        get: operations["FileController_getById"];
        put?: never;
        post?: never;
        /** DELETE /files/:id — 본인 소유 파일 삭제 */
        delete: operations["FileController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /files/:id/confirm — 업로드 확정(PENDING→UPLOADED + size), 소유자 전용 */
        post: operations["FileController_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/banners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /admin/banners — 전체 목록 (관리자) */
        get: operations["AdminBannerController_listAll"];
        put?: never;
        /** POST /admin/banners — 배너 생성 */
        post: operations["AdminBannerController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/banners/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** DELETE /admin/banners/:id — 배너 삭제 */
        delete: operations["AdminBannerController_remove"];
        options?: never;
        head?: never;
        /** PATCH /admin/banners/:id — 배너 부분 수정 */
        patch: operations["AdminBannerController_update"];
        trace?: never;
    };
    "/banners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /banners — 활성 + 노출기간 내 배너만 sortOrder 순 (공개, 인증 불필요) */
        get: operations["BannerController_listPublic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /admin/stats/overview — 플랫폼 요약 통계 (관리자) */
        get: operations["AdminStatsController_getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /seller/stats — 본인 판매 요약 (APPROVED 판매자 본인) */
        get: operations["SellerStatsController_getMyStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/sellers/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /admin/sellers/pending — 승인 대기 판매자 목록 */
        get: operations["AdminController_listPendingSellers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/sellers/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /admin/sellers/:id/approve — 판매자 승인 (seller 도메인 재사용) + 감사 로그 기록 */
        post: operations["AdminController_approveSeller"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /admin/users — 사용자 목록 (cursor 페이지네이션) */
        get: operations["AdminController_listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /admin/audit-logs — 관리자 조치 감사 로그 (최신순, 013) */
        get: operations["AdminController_listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OrderItemInput: {
            variantId: string;
            quantity: number;
        };
        CreateOrderDto: {
            items: components["schemas"]["OrderItemInput"][];
            shippingAddress: Record<string, never>;
            /** @description 쿠폰 적용 시 userCoupon ID. 미전달 시 할인 없음 (SEC-FIND-004: 금액 직접 지정 금지) */
            userCouponId?: string;
        };
        OrderAddressSnapshotResponse: {
            recipientName: string;
            phone: string;
            zipCode: string;
            address1: string;
            address2?: string | null;
        };
        OrderResponse: {
            id: string;
            /** @description cross-schema plain String — users.users.id (P-001) */
            userId: string;
            /** @enum {string} */
            status: "pending" | "confirmed" | "preparing" | "shipped" | "delivered" | "completed" | "cancelled";
            /**
             * @description 금전 — 총 주문 금액 (P-005)
             * @example 30000.00
             */
            totalAmount: string;
            /**
             * @description 금전 — 할인 금액 (P-005)
             * @example 0
             */
            discountAmount: string;
            /** @description 주문 시점 배송지 스냅샷 (FR-016) */
            shippingAddressSnapshot: components["schemas"]["OrderAddressSnapshotResponse"];
            /** Format: date-time */
            deliveredAt?: string | null;
            /** Format: date-time */
            completedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        OrderListResponse: {
            items: components["schemas"]["OrderResponse"][];
            /** @description 다음 페이지 cursor (없으면 null) */
            nextCursor?: string | null;
        };
        OrderItemResponse: {
            id: string;
            orderId: string;
            variantId: string;
            productId: string;
            /** @description cross-schema plain String — users.sellers.id (P-001) */
            sellerId: string;
            quantity: number;
            /**
             * @description 금전 — 주문 시점 단가 스냅샷 (P-005)
             * @example 30000.00
             */
            unitPrice: string;
            optionName: string;
            optionValue: string;
            productTitle: string;
        };
        OrderDetailResponse: {
            id: string;
            /** @description cross-schema plain String — users.users.id (P-001) */
            userId: string;
            /** @enum {string} */
            status: "pending" | "confirmed" | "preparing" | "shipped" | "delivered" | "completed" | "cancelled";
            /**
             * @description 금전 — 총 주문 금액 (P-005)
             * @example 30000.00
             */
            totalAmount: string;
            /**
             * @description 금전 — 할인 금액 (P-005)
             * @example 0
             */
            discountAmount: string;
            /** @description 주문 시점 배송지 스냅샷 (FR-016) */
            shippingAddressSnapshot: components["schemas"]["OrderAddressSnapshotResponse"];
            /** Format: date-time */
            deliveredAt?: string | null;
            /** Format: date-time */
            completedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            items: components["schemas"]["OrderItemResponse"][];
        };
        RegisterSellerDto: {
            businessName: string;
            businessNumber: string;
            representativeName: string;
            contactPhone?: string;
            businessAddress?: string;
        };
        UpdateSellerDto: {
            businessName?: string;
            businessNumber?: string;
            representativeName?: string;
            contactPhone?: string | null;
            businessAddress?: string | null;
        };
        RejectSellerDto: {
            rejectReason: string;
        };
        ProductSummaryResponse: {
            id: string;
            /** @description cross-schema plain String — users.sellers.id (P-001) */
            sellerId: string;
            categoryId: string;
            title: string;
            description?: string | null;
            /**
             * @description 금전 — Decimal 직렬화 문자열 (P-005)
             * @example 30000.00
             */
            price: string;
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE" | "OUT_OF_STOCK" | "INACTIVE";
            /** Format: date-time */
            createdAt: string;
        };
        ProductListResponse: {
            items: components["schemas"]["ProductSummaryResponse"][];
            /** @description 다음 페이지 cursor (없으면 null) */
            nextCursor?: string | null;
        };
        ProductImageResponse: {
            id: string;
            productId: string;
            url: string;
            displayOrder: number;
        };
        VariantResponse: {
            id: string;
            productId: string;
            optionName: string;
            optionValue: string;
            sku: string;
            /**
             * @description 금전 — Decimal 직렬화 문자열 (P-005)
             * @example 30000.00
             */
            price: string;
        };
        ProductDetailResponse: {
            id: string;
            /** @description cross-schema plain String — users.sellers.id (P-001) */
            sellerId: string;
            categoryId: string;
            title: string;
            description?: string | null;
            /**
             * @description 금전 — Decimal 직렬화 문자열 (P-005)
             * @example 30000.00
             */
            price: string;
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE" | "OUT_OF_STOCK" | "INACTIVE";
            /** Format: date-time */
            createdAt: string;
            images: components["schemas"]["ProductImageResponse"][];
            variants: components["schemas"]["VariantResponse"][];
        };
        CreateProductDto: {
            categoryId: string;
            title: string;
            description?: string;
            price: number;
        };
        UpdateProductDto: {
            categoryId?: string;
            title?: string;
            description?: string | null;
            price?: number;
        };
        CreateVariantDto: {
            optionName: string;
            optionValue: string;
            sku: string;
            price: number;
            initialStock?: number;
        };
        UpdateVariantDto: {
            optionName?: string;
            optionValue?: string;
            sku?: string;
            price?: number;
        };
        AddImageDto: {
            /** Format: uri */
            url: string;
            displayOrder?: number;
        };
        CategoryResponse: {
            id: string;
            name: string;
            slug: string;
            displayOrder: number;
        };
        StockInDto: {
            quantity: number;
        };
        CartItemResponse: {
            variantId: string;
            productId: string;
            /** @description cross-schema plain String — users.sellers.id (P-001) */
            sellerId: string;
            quantity: number;
            /**
             * @description 금전 — 단가 스냅샷 (P-005)
             * @example 30000.00
             */
            unitPrice: string;
            optionName: string;
            optionValue: string;
            productTitle: string;
            sku: string;
        };
        CartResponse: {
            items: components["schemas"]["CartItemResponse"][];
        };
        AddCartItemDto: {
            variantId: string;
            quantity: number;
        };
        UpdateCartItemDto: {
            quantity: number;
        };
        CreateCouponDto: {
            /** @enum {string} */
            type: "FIXED" | "PERCENTAGE";
            /** @description 정액(원) 또는 비율(1~100, 정수). Decimal 문자열로 전달 */
            discountValue: string;
            /** @description PERCENTAGE 전용 최대 할인 금액 상한 */
            maxDiscountAmount?: string;
            /** @description 최소 주문 금액 조건 */
            minOrderAmount?: string;
            expiresAt: string;
            totalQuantity?: number;
            description?: string;
        };
        CouponResponse: {
            id: string;
            /** @enum {string} */
            issuerType: "ADMIN" | "SELLER";
            /** @description ADMIN: admin userId, SELLER: users.sellers.id (P-001) */
            issuerId: string;
            /** @enum {string} */
            type: "FIXED" | "PERCENTAGE";
            /**
             * @description 금전/할인율 — Decimal 직렬화 문자열 (P-005)
             * @example 5000.00
             */
            discountValue: string;
            /** @description 금전 — PERCENTAGE 최대 할인 상한 (P-005) */
            maxDiscountAmount?: string | null;
            /** @description 금전 — 최소 주문 금액 (P-005) */
            minOrderAmount?: string | null;
            /** Format: date-time */
            expiresAt: string;
            /** @description 발급 한도 (null=무제한) */
            totalQuantity?: number | null;
            issuedCount: number;
            description?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CouponListResponse: {
            items: components["schemas"]["CouponResponse"][];
            nextCursor?: string | null;
        };
        IssueCouponDto: {
            targetUserId: string;
        };
        UserCouponResponse: {
            id: string;
            couponId: string;
            /** @enum {string} */
            status: "unused" | "used" | "expired";
            /** @description 사용된 주문 id (FR-016) */
            usedOrderId?: string | null;
            /** Format: date-time */
            createdAt: string;
            coupon: components["schemas"]["CouponResponse"];
        };
        CreatePaymentDto: {
            orderId: string;
            /**
             * Format: uuid
             * @description 클라이언트 생성 UUID v4 — 멱등성 보장 (ADR-006). 헤더 미전달 시 body 값 사용.
             */
            idempotencyKey: string;
        };
        RegisterDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshDto: {
            refreshToken: string;
        };
        UpdateProfileDto: {
            name?: string;
            phone?: string;
        };
        CreateAddressDto: {
            recipientName: string;
            phone: string;
            zipCode: string;
            address1: string;
            address2?: string;
            isDefault?: boolean;
        };
        UpdateAddressDto: {
            recipientName?: string;
            phone?: string;
            zipCode?: string;
            address1?: string;
            address2?: string | null;
        };
        AddWishlistDto: {
            productId: string;
        };
        CreateShipmentDto: {
            /** @description 송장을 등록할 주문 ID */
            orderId: string;
            /** @description 택배사 */
            carrier: string;
            /** @description 운송장 번호 */
            trackingNumber: string;
        };
        ShipmentResponse: {
            id: string;
            /** @description cross-module plain String — orders.orders.id (P-001) */
            orderId: string;
            /** @enum {string} */
            status: "preparing" | "shipped" | "in_transit" | "delivered";
            carrier: string;
            trackingNumber: string;
            /** Format: date-time */
            shippedAt?: string | null;
            /** Format: date-time */
            deliveredAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateShipmentStatusDto: {
            /**
             * @description 변경할 배송 상태 (shipped · in_transit · delivered)
             * @enum {string}
             */
            status: "preparing" | "shipped" | "delivered" | "in_transit";
            /** @description 추적 이력에 남길 설명 (선택) */
            description?: string;
        };
        ShipmentTrackingResponse: {
            id: string;
            shipmentId: string;
            /** @enum {string} */
            status: "preparing" | "shipped" | "in_transit" | "delivered";
            description: string;
            /** Format: date-time */
            occurredAt: string;
        };
        CreateSettlementDto: {
            /** @description 정산 대상 판매자 ID (users.sellers.id) */
            sellerId: string;
            /** @description 정산 기간 시작 (ISO 8601) */
            periodStart: string;
            /** @description 정산 기간 종료 (ISO 8601) */
            periodEnd: string;
        };
        CreateReviewDto: {
            orderItemId: string;
            /** @description 평점 1~5 정수 (FR-022·SC-034) */
            rating: number;
            content: string;
        };
        ReviewResponse: {
            id: string;
            /** @description orders.order_items.id — 1 orderItem 1 리뷰 (P-001) */
            orderItemId: string;
            orderId: string;
            userId: string;
            productId: string;
            /** @description users.sellers.id (P-001) */
            sellerId: string;
            /** @description 평점 1~5 */
            rating: number;
            content: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateReviewDto: {
            rating?: number;
            content?: string;
        };
        ReviewListResponse: {
            items: components["schemas"]["ReviewResponse"][];
            nextCursor?: string | null;
        };
        ProductCardResponse: {
            id: string;
            /** @description cross-schema plain String — users.sellers.id (P-001) */
            sellerId: string;
            categoryId: string;
            title: string;
            description?: string | null;
            /**
             * @description 금전 — Decimal 직렬화 문자열 (P-005)
             * @example 30000.00
             */
            price: string;
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE" | "OUT_OF_STOCK" | "INACTIVE";
            /** Format: date-time */
            createdAt: string;
            images: components["schemas"]["ProductImageResponse"][];
        };
        SearchProductsResponse: {
            items: components["schemas"]["ProductCardResponse"][];
            total: number;
            page: number;
            size: number;
        };
        PresignDto: {
            /** @enum {string} */
            purpose: "PRODUCT_IMAGE" | "REVIEW_IMAGE" | "PROFILE";
            contentType: string;
        };
        ConfirmFileDto: {
            /** @description 업로드된 파일 크기(byte). 상한은 service(MAX_FILE_SIZE_BYTES)에서 검증. */
            size: number;
        };
        CreateBannerDto: {
            title: string;
            imageUrl: string;
            /** @description 클릭 이동 대상 URL (없으면 비링크 배너) */
            linkUrl?: string;
            /**
             * @description 노출 위치 (미지정 시 기본 MAIN_TOP)
             * @enum {string}
             */
            position?: "MAIN_TOP" | "MAIN_MIDDLE" | "MAIN_BOTTOM" | "SIDEBAR";
            /** @description 동일 위치 내 정렬 순서 (오름차순) */
            sortOrder?: number;
            /** @description 활성 여부 (미지정 시 기본 true) */
            isActive?: boolean;
            /** @description 노출 시작 (ISO 8601, null=즉시) */
            startsAt?: string;
            /** @description 노출 종료 (ISO 8601, null=무제한) */
            endsAt?: string;
        };
        UpdateBannerDto: {
            title?: string;
            imageUrl?: string;
            linkUrl?: string | null;
            /** @enum {string} */
            position?: "MAIN_TOP" | "MAIN_MIDDLE" | "MAIN_BOTTOM" | "SIDEBAR";
            sortOrder?: number;
            isActive?: boolean;
            startsAt?: string | null;
            endsAt?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    OrderController_listMyOrders: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponse"];
                };
            };
        };
    };
    OrderController_createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    OrderController_getDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailResponse"];
                };
            };
        };
    };
    OrderController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SellerOrderController_listSellerOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SellerOrderController_getSellerOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    SellerOrderController_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SellerController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterSellerDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    SellerController_getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    SellerController_updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSellerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    SellerController_getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    SellerController_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    SellerController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectSellerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ProductController_listPublic: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
        };
    };
    ProductController_createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_getDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailResponse"];
                };
            };
        };
    };
    ProductController_updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_addVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVariantDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_deleteVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                variantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_updateVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                variantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVariantDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_addImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddImageDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_deleteImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                imageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"][];
                };
            };
        };
    };
    SellerProductController_listMyProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InventoryController_stockIn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockInDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InventoryController_getStock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
        };
    };
    CartController_getCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
        };
    };
    CartController_addItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCartItemDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartItemResponse"][];
                };
            };
        };
    };
    CartController_updateQuantity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCartItemDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartItemResponse"][];
                };
            };
        };
    };
    CartController_removeItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminCouponController_listCoupons: {
        parameters: {
            query?: {
                cursor?: string;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CouponListResponse"];
                };
            };
        };
    };
    AdminCouponController_createCoupon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCouponDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CouponResponse"];
                };
            };
        };
    };
    AdminCouponController_issueCoupon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueCouponDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCouponResponse"];
                };
            };
        };
    };
    SellerCouponController_listCoupons: {
        parameters: {
            query?: {
                cursor?: string;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CouponListResponse"];
                };
            };
        };
    };
    SellerCouponController_createCoupon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCouponDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CouponResponse"];
                };
            };
        };
    };
    SellerCouponController_issueCoupon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueCouponDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCouponResponse"];
                };
            };
        };
    };
    UserCouponController_listMyCoupons: {
        parameters: {
            query?: {
                status?: "unused" | "used" | "expired";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCouponResponse"][];
                };
            };
        };
    };
    PaymentController_pay: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePaymentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    UserController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    UserController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    UserController_listAddresses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    UserController_createAddress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAddressDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    UserController_deleteAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_updateAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAddressDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    UserController_setDefaultAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_listWishlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    UserController_addWishlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddWishlistDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    UserController_removeWishlist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_listRecentViews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    ShippingController_getByOrder: {
        parameters: {
            query: {
                orderId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 송장 미존재 시 null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentResponse"];
                };
            };
        };
    };
    ShippingController_createShipment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShipmentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentResponse"];
                };
            };
        };
    };
    ShippingController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateShipmentStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentResponse"];
                };
            };
        };
    };
    ShippingController_getTracking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentTrackingResponse"][];
                };
            };
        };
    };
    SettlementController_listMySettlements: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SettlementController_createSettlement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSettlementDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AdminSettlementController_listAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReviewController_createReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
        };
    };
    ReviewController_deleteReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReviewController_updateReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
        };
    };
    ReviewController_listMyReviews: {
        parameters: {
            query?: {
                cursor?: string;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewListResponse"];
                };
            };
        };
    };
    ProductReviewController_listProductReviews: {
        parameters: {
            query?: {
                cursor?: string;
                take?: number;
            };
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewListResponse"];
                };
            };
        };
    };
    SearchController_searchProducts: {
        parameters: {
            query?: {
                /** @description 키워드 — 상품명 부분일치 */
                q?: string;
                categoryId?: string;
                /** @description 최소 가격 — 금전 문자열(부동소수점 오차 방지, Decimal 변환 전제) */
                minPrice?: string;
                /** @description 최대 가격 */
                maxPrice?: string;
                sort?: "latest" | "price_asc" | "price_desc";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchProductsResponse"];
                };
            };
        };
    };
    NotificationController_list: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    NotificationController_markAllRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationController_markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FileController_presign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    FileController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FileController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FileController_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmFileDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminBannerController_listAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminBannerController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBannerDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminBannerController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminBannerController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBannerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BannerController_listPublic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminStatsController_getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    SellerStatsController_getMyStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AdminController_listPendingSellers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    AdminController_approveSeller: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AdminController_listUsers: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_listAuditLogs: {
        parameters: {
            query?: {
                limit?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
