/**
 * 디자인 토큰 빌드 (DESIGN-PLAN §3) — W3C DTCG 토큰 → Style Dictionary →
 *   - build/web/tokens.css         : :root(light) + .dark(dark) CSS 변수 (semantic만 노출)
 *   - build/web/tailwind-preset.cjs: Tailwind theme.extend (var() 참조)
 *   - build/flutter/light_tokens.dart / dark_tokens.dart : Dart 토큰 맵
 *
 * primitive 는 참조 전용(노출 안 함). theme 차이는 색상(semantic/color.*)만 분기한다.
 */
import StyleDictionary from 'style-dictionary';
import { readFileSync, writeFileSync, rmSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PRIMITIVE = 'tokens/primitive/*.json';
const SEMANTIC_BASE = 'tokens/semantic/base.json';
const isSemantic = (t) => t.filePath.includes('/semantic/');
const isSemanticColorDark = (t) => t.filePath.includes('/semantic/color.dark');

// ── Tailwind preset 포맷 (semantic → theme.extend, var() 참조) ────────────────
StyleDictionary.registerFormat({
  name: 'doa/tailwind-preset',
  format: ({ dictionary }) => {
    const colorCats = ['bg', 'fg', 'border', 'accent', 'success', 'warning', 'danger', 'info'];
    const colors = {};
    const borderRadius = {};
    const spacing = {};
    const fontSize = {};
    const transitionDuration = {};
    for (const t of dictionary.allTokens.filter(isSemantic)) {
      const ref = `var(--${t.name})`;
      const [cat, sub] = t.path;
      if (colorCats.includes(cat)) (colors[cat] ??= {})[sub] = ref;
      else if (cat === 'radius') borderRadius[sub] = ref;
      else if (cat === 'space') spacing[sub] = ref;
      else if (cat === 'text') fontSize[sub] = ref;
      else if (cat === 'motion') transitionDuration[sub] = ref;
    }
    const theme = { colors, borderRadius, spacing, fontSize, transitionDuration };
    return (
      '/** AUTO-GENERATED by @doa/design-tokens — do not edit. */\n' +
      `module.exports = { theme: { extend: ${JSON.stringify(theme, null, 2)} } };\n`
    );
  },
});

// ── Flutter Dart 포맷 (semantic 색상·치수 → const 맵) ─────────────────────────
const dartFormat = (className) => ({ dictionary }) => {
  const lines = [];
  for (const t of dictionary.allTokens.filter(isSemantic)) {
    const key = t.path.join('_');
    const v = t.$value ?? t.value;
    if (t.$type === 'color') {
      const hex = String(v).replace('#', '').toUpperCase();
      const argb = hex.length === 6 ? `0xFF${hex}` : `0x${hex}`;
      lines.push(`  static const Color ${key} = Color(${argb});`);
    } else if (t.$type === 'dimension') {
      lines.push(`  static const double ${key} = ${parseFloat(v)};`);
    }
  }
  return (
    '// AUTO-GENERATED by @doa/design-tokens — do not edit.\n' +
    "import 'package:flutter/material.dart';\n\n" +
    `class ${className} {\n${lines.join('\n')}\n}\n`
  );
};
StyleDictionary.registerFormat({ name: 'doa/dart-light', format: dartFormat('DoaLightTokens') });
StyleDictionary.registerFormat({ name: 'doa/dart-dark', format: dartFormat('DoaDarkTokens') });

function instance(theme) {
  const colorFile = `tokens/semantic/color.${theme}.json`;
  return new StyleDictionary({
    source: [PRIMITIVE, SEMANTIC_BASE, colorFile],
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath: 'build/web/',
        files: [
          {
            destination: theme === 'light' ? '_root.css' : '_dark.css',
            format: 'css/variables',
            filter: theme === 'light' ? isSemantic : isSemanticColorDark,
            options: { selector: theme === 'light' ? ':root' : '.dark', outputReferences: false },
          },
        ],
      },
      ...(theme === 'light'
        ? {
            tw: {
              transformGroup: 'css',
              buildPath: 'build/web/',
              files: [{ destination: 'tailwind-preset.cjs', format: 'doa/tailwind-preset' }],
            },
          }
        : {}),
      flutter: {
        transformGroup: 'js',
        buildPath: 'build/flutter/',
        files: [
          {
            destination: `${theme}_tokens.dart`,
            format: theme === 'light' ? 'doa/dart-light' : 'doa/dart-dark',
            filter: isSemantic,
          },
        ],
      },
    },
  });
}

await (await instance('light')).buildAllPlatforms();
await (await instance('dark')).buildAllPlatforms();

// 웹 CSS 결합: _root.css(light) + _dark.css(dark) → tokens.css
const webDir = resolve(__dirname, 'build/web');
const root = readFileSync(resolve(webDir, '_root.css'), 'utf8');
const dark = readFileSync(resolve(webDir, '_dark.css'), 'utf8');
writeFileSync(
  resolve(webDir, 'tokens.css'),
  `/** AUTO-GENERATED by @doa/design-tokens — do not edit. */\n${root}\n${dark}`,
);
rmSync(resolve(webDir, '_root.css'));
rmSync(resolve(webDir, '_dark.css'));

console.log('design-tokens built: build/web/{tokens.css,tailwind-preset.cjs}, build/flutter/{light,dark}_tokens.dart');
